"""empty message

Revision ID: 22e53a6a1a88
Revises: 82858cc21051
Create Date: 2024-02-23 20:46:38.768428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22e53a6a1a88'
down_revision = '82858cc21051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.drop_column('D')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('D', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
